/**
 * Centralized export of all Mongoose models
 * Use this instead of importing each model individually
 */

export {
  User,
  Address,
  Category,
  Product,
  CategoryAttribute,
  CategoryAttributeValue,
  ProductAttributeValue,
  ProductVariant,
  Cart,
  CartItem,
  Order,
  OrderItem,
  Wishlist,
  Review,
  Notification,
  Otp,
  TempUpdate,
  Coupon,
  StaffProfile,
  AuditLog,
  AppSetting,
  PaymentLog,
  HomeBanner,
  CustomerTracker,
  // Aliases
  Attribute,
  AttributeValue,
  CompanySettings,
  PasswordReset,
  // Also export types
  type IUser,
  type IAddress,
  type ICategory,
  type IProduct,
  type ICategoryAttribute,
  type ICategoryAttributeValue,
  type IProductAttributeValue,
  type IProductVariant,
  type ICart,
  type ICartItem,
  type IOrder,
  type IOrderItem,
  type IWishlist,
  type IReview,
  type INotification,
  type IOtp,
  type ITempUpdate,
  type ICoupon,
  type IStaffProfile,
  type IAuditLog,
  type IAppSetting,
  type IPaymentLog,
  type IHomeBanner,
  type ICustomerTracker,
  // Also export enums
  RoleEnum,
  OrderStatusEnum,
  PaymentStatusEnum,
  PaymentMethodEnum,
  NotificationTypeEnum,
  AttributeTypeEnum,
} from "../models/mongoose";
